Use Flashbar in place of ValidationErrors component
aws/aws-parallelcluster-ui pull request #121
Opened 2023-03-14 18:08 UTC by tmscarla

## Description

Currently, upon a dry-run/creation of a cluster, we are showing errors through a custom `ValidationErrors` component, which displays errors in a styled `div`.

In order to be compliant with Cloudscape, we need to display errors leveraging `Flashbar` component, at the top YAML code editor.

This PR introduces Cloudscape `Flashbar` component in place of `ValidationErrors`.

## How Has This Been Tested?

* E2E tests
* Unit tests
* Manual tests
   * Verified that `Flashbar` is displayed with success message (with and without validation warnings)
   * Verified that `Flashbar` is displayed with error messages upon cluster creation
   * Verified that `Flashbar` is displayed with error messages upon cluster editing

## References

* https://cloudscape.design/components/flashbar

## Screenshots

<img width="1728" alt="Screenshot 2023-03-14 at 17 41 27" src="https://user-images.githubusercontent.com/25930133/225076599-ec904e5d-c377-4945-97b6-1b60471117af.png">

## PR Quality Checklist

- [x] I added tests to new or existing code
- [x] I removed hardcoded strings and used [`react-i18next`](https://react.i18next.com/) library ([useTranslation hook](https://react.i18next.com/latest/usetranslation-hook) and/or [Trans component](https://react.i18next.com/latest/trans-component)), see an example [here](https://github.com/aws/aws-parallelcluster-ui/commit/a6f1e2aa46b245b5bf7500a04b83195477a5cfa5)
- [ ] I made sure no sensitive info gets logged at any time in the codebase (see [here](https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html)) (e.g. no user info or details, no stacktraces, etc.)
- [ ] I checked that infrastructure/update_infrastructure.sh runs without any error
- [x] I checked that `npm run build` builds without any error
- [x] I checked that clusters are listed correctly
- [ ] I checked that a new cluster can be created (config is produced and dry run passes)
- [ ] I checked that login and logout work as expected

In order to increase the likelihood of your contribution being accepted, please make sure you have read both the [Contributing Guidelines](../CONTRIBUTING.md) and the [Project Guidelines](../PROJECT_GUIDELINES.md)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-03-15 09:36 UTC, mtfranchetto requested changes

2023-03-15 09:36 UTC, mtfranchetto commented on frontend/src/old-pages/Configure/Create.tsx
> +      header: 'Success',
todo: avoid hardcoding labels! Put this under `strings.json`

2023-03-15 09:36 UTC, mtfranchetto commented on frontend/src/old-pages/Configure/Create.tsx
> +      onDismiss: (): void =>
suggestion: all messages are dismissable in the same way but the logic is duplicated. It can be extracted and reused with a simple function similar to this one
```typescript
function dismissableMessage(messageDefinition: MessageDefinition, setFlashbarItems): MessageDefinition {
  return {
    ...messageDefinition,
    dismissable: true,
    onDismiss: () =>  setFlashbarItems(
      items => items.filter(item => item.id !== messageDefinition.id),
    ),
  }
}

configErrors?.forEach((error: ConfigError, index: number) => {
  items.push(dismissableMessage({
    type: error.level.toLowerCase() as FlashbarProps.Type,
    ...
  }))
});

```

2023-03-15 13:20 UTC, tmscarla commented on frontend/src/old-pages/Configure/Create.tsx
> +      header: 'Success',
Yes, forgot to remove the hardcoded strings

2023-03-16 08:15 UTC, BarcoMasile commented on frontend/src/old-pages/Configure/Create.types.ts
super small nipitck, feel free to ignore: this file seems related to error stuff only, I would rename it accordingly, like `Create.errors.ts` or `Create.error.types.ts`

2023-03-16 08:21 UTC, BarcoMasile commented on frontend/src/old-pages/Configure/__tests__/errorsToFlashbarItems.test.ts
> +  describe('when errors contain "succeeded" in the error message', () => {
suggestion(non-blocking): when describing test cases, try not to refer to implementation details.
In this case, it could be `when the error message describes a successful outcome`

This way if implementation changes, we don't have to also refactor the test description

2023-03-16 14:14 UTC, BarcoMasile approved these changes

2023-03-16 14:16 UTC, mtfranchetto approved these changes

2023-03-16 14:22 UTC, merged