[PCUI]Add PermissionBoundary for every role and IAM prefix for every …
aws/aws-parallelcluster-ui pull request #252
Opened 2023-08-10 23:53 UTC by kkolur5

…role and policy.

## Description

[PCUI]Add PermissionBoundary for every role and IAM prefix for every role and policy.

## Changes

## How Has This Been Tested?

## References

## PR Quality Checklist

- [ ] I added tests to new or existing code
- [ ] I removed hardcoded strings and used [`react-i18next`](https://react.i18next.com/) library ([useTranslation hook](https://react.i18next.com/latest/usetranslation-hook) and/or [Trans component](https://react.i18next.com/latest/trans-component)), see an example [here](https://github.com/aws/aws-parallelcluster-ui/commit/a6f1e2aa46b245b5bf7500a04b83195477a5cfa5)
- [ ] I made sure no sensitive info gets logged at any time in the codebase (see [here](https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html)) (e.g. no user info or details, no stacktraces, etc.)
- [ ] I made sure that any [GitHub issue](https://github.com/aws/aws-parallelcluster-ui/issues) solved by this PR is correctly linked
- [ ] I checked that infrastructure/update_infrastructure.sh runs without any error
- [ ] I checked that `npm run build` builds without any error
- [ ] I checked that clusters are listed correctly
- [ ] I checked that a new cluster can be created (config is produced and dry run passes)
- [ ] I checked that login and logout work as expected

In order to increase the likelihood of your contribution being accepted, please make sure you have read both the [Contributing Guidelines](../CONTRIBUTING.md) and the [Project Guidelines](../PROJECT_GUIDELINES.md)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-08-11 07:38 UTC, gmarciani requested changes
Apart from the inline comments, we should include an entry in the changelog for this change.

2023-08-11 07:38 UTC, gmarciani commented on infrastructure/parallelcluster-ui-cognito.yaml
> +  PermissionBoundaryARN:
**Important Note**
According to the final PM decision, we will have 3 different parameters for permissions boundary:
* one for the UI infrastructure
* one for API infrastructure
* one for API role conditions

Given that we are still iterating on the final decision, let's proceed with the original approach, that is the one you're proposing here but let's be prepared to iterate on that.

2023-08-11 07:38 UTC, gmarciani commented on infrastructure/parallelcluster-ui-cognito.yaml
> +    ConstraintDescription: "The value must be a valid ARN in the format: arn:.*:iam:.*:policy/PolicyNameParameter"
I'd say a valid IAM policy ARN rather than a valid ARN

2023-08-11 07:38 UTC, gmarciani commented on infrastructure/parallelcluster-ui-cognito.yaml
> +    Description: 'Prefix for IAM roles and policies'
I'd be more specific, like "Prefix for IAM roles and policies name"

2023-08-11 07:38 UTC, gmarciani commented on infrastructure/parallelcluster-ui.yaml
> +        CustomBucket: kkolur-pcapi
We must remove your testing bucket from here

2023-08-11 07:38 UTC, gmarciani commented on infrastructure/parallelcluster-ui.yaml
> +        CreateApiUserRole: True
Why changing this from false to true?

2023-08-11 07:38 UTC, gmarciani commented on infrastructure/parallelcluster-ui.yaml
> +        PoliciesTemplateUri: https://kkolur-pcapi.s3.amazonaws.com/parallelcluster-policies.yaml
We should remove your testing template

2023-08-11 07:38 UTC, gmarciani commented on infrastructure/parallelcluster-ui.yaml
> +      TemplateURL: https://kkolur-pcapi.s3.amazonaws.com/parallelcluster-api.yaml
Same as above, let's restore the original value without testing values

2023-08-11 07:38 UTC, gmarciani commented on infrastructure/parallelcluster-ui.yaml
> +      RoleName: !Sub ${IAMRoleAndPolicyPrefix}ImageBuilderInstanceRole
**Breaking Change**
Currently, CloudFormation adds a disambiguator as a suffix for the role name. This allows customers to deploy the same template multiple times in the same account and region without resource collisions.
We should keep this by adding a disambiguator as a role name suffix, e.g. stack id.

Example of disambiguation:

```
RepositoryName: !Sub
        - 'parallelcluster-ui-${StackIdSuffix}'
        - { StackIdSuffix: !Select [2, !Split ['/', !Ref 'AWS::StackId']] }
```

2023-08-11 07:38 UTC, gmarciani commented on infrastructure/parallelcluster-ui.yaml
> +        ApiDefinitionS3Uri: s3://kkolur-pcapi/ParallelCluster.openapi.yaml
Same as above, let's restore the original values

2023-08-11 10:32 UTC, kkolur5 commented on infrastructure/parallelcluster-ui.yaml
> +        PoliciesTemplateUri: https://kkolur-pcapi.s3.amazonaws.com/parallelcluster-policies.yaml
when I was deploying the CF stack for PCUI, I noticed that there was a role apart of PC API that couldn't be found on the stack and that was ParallelClusterApiUserRole  because the CreateApiUserRole: was set to false. So once I set it to True, the IAM role appeared and I could see the prefix and PB applied correctly.

2023-08-11 11:22 UTC, kkolur5 commented on infrastructure/parallelcluster-ui.yaml
> +        CreateApiUserRole: True
when I was deploying the CF stack for PCUI, I noticed that there was a role apart of PC API that couldn't be found on the stack and that was ParallelClusterApiUserRole because the CreateApiUserRole: was set to false. So once I set it to True, the IAM role appeared and I could see the prefix and PB applied correctly.

2023-08-18 15:58 UTC, hanwen-pcluste commented on infrastructure/parallelcluster-ui.yaml
> +        - 'https://${Bucket}.s3.amazonaws.com/parallelcluster-ui-cognito.yaml'
Why is this change necessary?

2023-08-18 16:25 UTC, kkolur5 commented on infrastructure/parallelcluster-ui.yaml
> +        - 'https://${Bucket}.s3.amazonaws.com/parallelcluster-ui-cognito.yaml'
I think I forgot to change that back to what it was before sorry

2023-08-18 16:41 UTC, hanwen-pcluste approved these changes

2023-08-18 16:46 UTC, kkolur5 reviewed
Request addressed

2023-08-18 16:52 UTC, closed without merging