[Bump jinja2, axios for follow-redirects
aws/aws-parallelcluster-ui pull request #306
Opened 2024-02-12 18:07 UTC by judysng

## Description

## Changes

## How Has This Been Tested?

## References

## PR Quality Checklist

- [ ] I added tests to new or existing code
- [ ] I removed hardcoded strings and used [`react-i18next`](https://react.i18next.com/) library ([useTranslation hook](https://react.i18next.com/latest/usetranslation-hook) and/or [Trans component](https://react.i18next.com/latest/trans-component)), see an example [here](https://github.com/aws/aws-parallelcluster-ui/commit/a6f1e2aa46b245b5bf7500a04b83195477a5cfa5)
- [ ] I made sure no sensitive info gets logged at any time in the codebase (see [here](https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html)) (e.g. no user info or details, no stacktraces, etc.)
- [ ] I made sure that any [GitHub issue](https://github.com/aws/aws-parallelcluster-ui/issues) solved by this PR is correctly linked
- [ ] I checked that infrastructure/update_infrastructure.sh runs without any error
- [ ] I checked that `npm run build` builds without any error
- [ ] I checked that clusters are listed correctly
- [ ] I checked that a new cluster can be created (config is produced and dry run passes)
- [ ] I checked that login and logout work as expected

In order to increase the likelihood of your contribution being accepted, please make sure you have read both the [Contributing Guidelines](../CONTRIBUTING.md) and the [Project Guidelines](../PROJECT_GUIDELINES.md)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-02-13 08:50 UTC, gmarciani requested changes

2024-02-13 08:50 UTC, gmarciani commented on requirements.txt
> +jinja2==3.1.3
We should not directly change the `requirements.txt`, but instead:
1. Add the dependency constraint in `requirements.ini`
2. Run `pip-compile` to let it generate the requirements.txt, as explained [here](https://github.com/gmarciani/aws-parallelcluster-ui/blob/main/DEVELOPMENT.md?plain=1#L24-L37)

2024-02-13 08:50 UTC, gmarciani commented on requirements.txt
> +jinja2==3.1.3
Made deps management instructions more highlighted in https://github.com/aws/aws-parallelcluster-ui/pull/308,

2024-02-13 08:50 UTC, gmarciani commented on frontend/package.json
> +    "axios": "^1.6.4",
*Best Practice*
When changing dependencies it's always preferable to do it in separated commits, one per dependency. In this way the revert process in case of impactful upgrades will be easier.

2024-02-13 08:50 UTC, gmarciani commented on frontend/package.json
> +    "axios": "^1.6.4",
I think we need to update the attribution document as well [here](https://github.com/aws/aws-parallelcluster-ui/blob/ef538bd24fa936b889e287f6a088dfd3c3b188ac/frontend/resources/attributions/npm-python-attributions.txt#L2265-L2267).

I think we missed to update it in the past, so my suggestion is to update axios in the attribution doc and add a follow up activity to update all deps in the attribution doc.

2024-02-13 11:41 UTC, gmarciani commented
Let's mention in the PR that upgrading jinja to 3.1.3 will also fix [CVE-2024-22195](https://github.com/aws/aws-parallelcluster-ui/security/dependabot/28)

2024-02-14 01:05 UTC, judysng commented on requirements.txt
> +jinja2==3.1.3
Thanks, updated flask in `requirements.txt` and ran `pip-compile`

2024-02-14 01:32 UTC, judysng commented on frontend/package.json
> +    "axios": "^1.6.4",
Sounds good, I made a separate PR for updating axios (with updating axios in attribution doc) here: https://github.com/aws/aws-parallelcluster-ui/pull/309

I will make another PR for updating the other parts in the attribution doc once these have been merged.

2024-02-14 09:05 UTC, gmarciani approved these changes

2024-02-14 20:59 UTC, merged